baseURL = "https://kivalinagrove.com"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]  

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css" 
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "research"
  URL = "#research"
  weight = 2

  [[menu.header]]
  name = "Teaching"
  URL = "#teaching"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4


  [[menu.footer]]
  name = "Research"
  URL = "#research"
  weight = 2

  [[menu.footer]]
  name = "Teaching"
  URL = "#teaching"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4

 
[params] 

  sections = ["showcase", "about", "education", "client-and-work", "testimonial", "contact"]

  #googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  favicon = "img/favicon.ico"

  [params.logo]
    text1 = "Kivalina"
    text2 = "Grove"

  [params.footer]
      copyright = "© Kivalina Grove. All rights reserved."
      [params.footer.radity_logo]
        x = "img/codedby2.png"
        _2x = "img/codedby2.png"
        alt = "Radiation Hugo Theme by Radity"
